version: '3'
services:
  api:
    image: node:12.8.0
    depends_on:
      - storage
    environment:
      - TERM=xterm
    volumes:
      - ./:/app
    expose:
      - 3000
    networks:
      default:
        aliases:
          - codemonx-telegram-bot
    command: sh -c 'cd /app && yarn && yarn build && NODE_ENV=production yarn start'
    restart: always

  storage:
    image: mongo:4.2.0
    environment:
      - MONGO_INITDB_DATABASE=codemonx
      - MONGO_INITDB_ROOT_USERNAME=codemonx
      - MONGO_INITDB_ROOT_PASSWORD=VW32n93N
    volumes:
      - storage-data:/data/db
    restart: always

volumes:
  storage-data:
