version: '3'
services:
  api:
    image: registry.gitlab.com/codemonx/upwork-telegram-bot
    depends_on:
      - storage
      - sql-storage
      - job-storage
    environment:
      - TERM=xterm
    networks:
      default:
        aliases:
          - upwork-telegram-bot
    restart: always

  storage:
    image: mongo:4.2.0
    environment:
      - TERM=xterm
      - MONGO_INITDB_DATABASE=codemonx
      - MONGO_INITDB_ROOT_USERNAME=codemonx
      - MONGO_INITDB_ROOT_PASSWORD=VW32n93N
    volumes:
      - storage-data:/data/db
    restart: always

  job-storage:
    image: redis:5.0.5-alpine
    environment:
      - TERM=xterm
    volumes:
      - job-storage-data:/data
    restart: always

  sql-storage:
    image: postgres:11.5-alpine
    environment:
      - TERM=xterm
      - POSTGRES_PASSWORD=VW32n93N
      - POSTGRES_USER=codemonx
      - POSTGRES_DB=codemonx
    volumes:
      - sql-storage-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

volumes:
  storage-data:
  job-storage-data:
  sql-storage-data:
